server:
  port: 8090

spring:
  session:
    timeout: 3m
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay=
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - RemoveRequestHeader=Cookie
      routes:
        # ১. Auth Server Route
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/roles/**, /users/**, /oauth2/**, /login/**, /logout/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServerCB
                fallbackUri: forward:/fallback/oneInAll

        # ২. Main Resource Service
        - id: resource-service
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/api/sample/**
          filters:
            # যদি রিসোর্স সার্ভিসের ভেতরে /api/sample পাথটি না থাকে তবে নিচের লাইনটি যোগ করুন
            # - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: resourceServiceCB
                fallbackUri: forward:/fallback/oneInAll

  security:
    oauth2:
      client:
        registration:
          api-gateway:
            provider: my-auth-server
            client-id: api-gateway
            client-secret: gateway-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, read, write
        provider:
          my-auth-server:
            issuer-uri: http://localhost:9000

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      authServerCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true
      resourceServiceCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        registerHealthIndicator: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.uuid}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG